### ISSUE TITLE
witness_node crashes on websocket connection if built in release mode

### ISSUE THREAD

**Issue by Troglodactyl** [cryptonomex/graphene#392] opened 2015-10-22 23:52 UTC
No problem in debug builds.

**Comment by wackou** [comment] 2015-10-23 15:22
that's most certainly a duplicate of this bug: https://github.com/cryptonomex/graphene/issues/365

**Comment by xeroc** [comment] 2015-10-27 10:24
Dublicate #365

**Closed as completed by xeroc** 2015-10-27 10:24 UTC
