### ISSUE TITLE
Failed p2p assertion: _closing_connections.find(peer_to_delete) == _closing_connections.end()

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#428] opened 2015-11-01 15:25 UTC
p2p assertion failed

witness_node: /home/cc/graphene/src/bitshares-2/libraries/net/node.cpp:1614: void graphene::net::detail::node_impl::schedule_peer_for_deletion(const peer_connection_ptr&): Assertion `_closing_connections.find(peer_to_delete) == _closing_connections.end()' failed.

The exception occurred with a long-running node running aa9ca16cb3b6ee576309f8915b164dafe577081d on BTS-2 network.  This node was stuck on block 284077 for some time prior to the crash (getting stuck was expected as it had not been upgraded for the hardfork).

**Comment by abitmore** [comment] 2015-11-01 17:37
Duplicate of #304

**Comment by abitmore** [comment] 2015-11-01 17:37
Looks like it always occurs when the client got stuck.

**Comment by abitmore** [comment] 2015-11-01 17:41
See also #288 #373 #378

**Comment by theoreticalbts** [comment] 2015-11-20 16:42
Closing all other issues, moving discussion here.

**Comment by vikramrajkumar** [comment] 2017-01-18 00:11
This issue was moved to bitshares/bitshares-core#120

**Closed as completed by vikramrajkumar** 2017-01-18 00:11 UTC
Labels: p2p
