### ISSUE TITLE
Segfault crash when syncing with 2.0.160103b

### ISSUE THREAD

**Issue by Troglodactyl** [cryptonomex/graphene#494] opened 2016-01-05 00:42 UTC
This crash is persistent.  Here's a backtrace:

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5428700 (LWP 14695)]
0x0000000000ef2e30 in websocketpp::processor::hybi13fc::http::detail::asio_with_stub_log::consume(unsigned char_, unsigned long, std::error_code&) ()
(gdb) bt
 #0  0x0000000000ef2e30 in websocketpp::processor::hybi13fc::http::detail::asio_with_stub_log::consume(unsigned char_, unsigned long, std::error_code&) ()
 #1  0x0000000000ed1ef9 in websocketpp::connectionfc::http::detail::asio_with_stub_log::handle_read_frame(std::error_code const&, unsigned long) ()
 #2  0x0000000000ea8624 in websocketpp::transport::asio::connectionfc::http::detail::asio_with_stub_log::transport_config::handle_async_read(boost::system::error_code const&, unsigned long) ()
 #3  0x0000000000ebd655 in boost::asio::detail::completion_handler<boost::asio::detail::binder2<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::connection<fc::http::detail::asio_with_stub_log::transport_config>::_)(boost::system::error_code const&, unsigned long)> (std::shared_ptrwebsocketpp::transport::asio::connection<fc::http::detail::asio_with_stub_log::transport_config >, std::_Placeholder<1>, std::_Placeholder<2>)>, boost::system::error_code, unsigned long> >::do_complete(boost::asio::detail::task_io_service_, boost::asio::detail::task_io_service_operation_, boost::system::error_code const&, unsigned long) ()
 #4  0x0000000000ebd8c6 in void boost::asio::detail::strand_service::dispatch<boost::asio::detail::binder2<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::connection<fc::http::detail::asio_with_stub_log::transport_config>::_)(boost::system::error_code const&, unsigned long)> (std::shared_ptrwebsocketpp::transport::asio::connection<fc::http::detail::asio_with_stub_log::transport_config >, std::_Placeholder<1>, std::_Placeholder<2>)>, boost::system::error_code, unsigned long> >(boost::asio::detail::strand_service::strand_impl_&, boost::asio::detail::binder2<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::connection<fc::http::detail::asio_with_stub_log::transport_config>::_)(boost::system::error_code const&, unsigned long)> (std::shared_ptrwebsocketpp::transport::asio::connection<fc::http::detail::asio_with_stub_log::transport_config >, std::_Placeholder<1>, std::_Placeholder<2>)>, boost::system::error_code, unsigned long>&) ()
 #5  0x0000000000ebd9f1 in std::_Function_handler<void (boost::system::error_code const&, unsigned long), boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::connection<fc::http::detail::asio_with_stub_log::transport_config>::_)(boost::system::error_code const&, unsigned long)> (std::shared_ptrwebsocketpp::transport::asio::connection<fc::http::detail::asio_with_stub_log::transport_config >, std::_Placeholder<1>, std::_Placeholder<2>)>, boost::asio::detail::is_continuation_if_running> >::_M_invoke(std::_Any_data const&, boost::system::error_code const&, unsigned long&&) ()
 #6  0x0000000000ebed8d in boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_at_least_t, websocketpp::transport::asio::custom_alloc_handler<std::function<void (boost::system::error_code const&, unsigned long)> > >::operator()(boost::system::error_code const&, unsigned long, int) ()
 #7  0x0000000000ebf34d in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_at_least_t, websocketpp::transport::asio::custom_alloc_handler<std::function<void (boost::system::error_code const&, unsigned long)> > > >::do_complete(boost::asio::detail::task_io_service_, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) ()
 #8  0x0000000000f0304b in fc::asio::default_io_service_scope::default_io_service_scope()::{lambda()# 1}::operator()() const ()
 #9  0x000000000103712d in thread_proxy ()
 #10 0x00007ffff79c14a4 in start_thread () from /usr/lib/libpthread.so.0
 #11 0x00007ffff60b713d in clone () from /usr/lib/libc.so.6
(gdb)

**Comment by Troglodactyl** [comment] 2016-01-05 04:19
Building in debug seems to resolve this issue, possibly related to #365?

**Comment by abitmore** [comment] 2016-01-05 14:59
https://github.com/bitshares/bitshares-2/commit/16b59e0b422c486238f4b6a09261dfd310b0c481#commitcomment-15240045

**Comment by theoreticalbts** [comment] 2016-01-05 21:07
Yeah, this was accidentally released with an old submodule version.  So this is actually duplicate of #365, but I'm leaving it open to remind myself to fix it.

**Comment by vikramrajkumar** [comment] 2017-01-18 01:00
This issue was moved to bitshares/bitshares-core#164

**Closed as completed by vikramrajkumar** 2017-01-18 01:00 UTC
