### ISSUE TITLE
[API] witness_node's get_account_history start parameter appears broken

### ISSUE THREAD

**Issue by wildbunny** [cryptonomex/graphene#394] opened 2015-10-23 14:54 UTC
Starting at operation 1, I get zero results from this call:
    {"id":4,"method":"call","params":[2,"get_account_history",["1.2.29495","1.11.10",20,"1.11.1"]]}

Starting at operation 0, I get 20 results from this call:
    {"id":4,"method":"call","params":[2,"get_account_history",["1.2.29495","1.11.10",20,"1.11.0"]]}

This appears to point to the start parameter not working correctly? We need this to be able to page through the data.

**Comment by xeroc** [comment] 2015-10-27 10:23
From https://bitsharestalk.org/index.php/topic,19374.msg249375.html#msg249375

```
The call returns ops for the given account such that

    stop < op.id <= start

except when start is 0, in which case it returns them all.  So by using operation 1, you will get no results unless the account you are querying is the account which performed operation 1.

Our API definitely has some rough edges.
```

**Comment by wildbunny** [comment] 2015-10-27 10:48
Xeroc, did you read down in that forum thread to the bottom? The functionality of this still appears broken to me.

**Comment by xeroc** [comment] 2015-10-27 11:41
Sorry ..

Have you tried it the other way round?

```
{"id":4,"method":"call","params":[2,"get_account_history",["1.2.29495","1.11.96290",10,"1.11.88751"]]}
```

**Comment by wildbunny** [comment] 2015-10-27 11:56
np - yeah, the other way around results in no results at all.

**Comment by theoreticalbts** [comment] 2015-11-20 17:04
Duplicate of #326

**Closed as completed by theoreticalbts** 2015-11-20 17:04 UTC
