### ISSUE TITLE
get_account_history is trying to decrypt memos when it should not even try

### ISSUE THREAD

**Issue by ByronAP** [cryptonomex/graphene#408] opened 2015-10-30 04:23 UTC
Calling get_account_history throws errors trying to decrypt the memo on sent transactions. It should not even try to decrypt these memos since the sending wallet can only encrypt the message not decrypt it. At the very least this error should be suppressed when the originating account is local.

**Comment by xeroc** [comment] 2015-10-30 08:24
Memos use a shared secret that can be derived from both ends knowing the pub key of the other party only .. I assume the cli-wallet tries to derive the shared secret in the wrong way such that it fails to load the other parties private key ..

**Comment by ByronAP** [comment] 2015-10-30 11:46
I haven't looked at the code to verify why but that seems like a logical reason

**Comment by theoreticalbts** [comment] 2015-10-30 13:12
Duplicate of #325.  Possibly related:  #377.

**Closed as completed by theoreticalbts** 2015-10-30 13:12 UTC
