### ISSUE TITLE
The "upgrade_account" command in the CLI fails to apply the upgrade

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene#527] opened 2016-01-21 00:19 UTC
Let's assume xxxx is a non-LTM account. 

When I run the CLI command:
`get_account xxxx`
I get:
`"membership_expiration_date": "1970-01-01T00:00:00"`
which is correct.

Now I upgrade xxxx to LTM:
`upgrade_account xxxx true`

When I run the CLI command again:
`get_account xxxx`
I still get:
`"membership_expiration_date": "1970-01-01T00:00:00"`
which is **incorrect** because I would expect to get:
`"membership_expiration_date": "1969-12-31T23:59:59"`
since xxxx has just been successfully upgraded.

It might have something to do with caching, as after restarting the CLI the problem always disappears - `get_account xxxx` gives the correct response.

---

This happens on Windows 10 64bit.

**Comment by xeroc** [comment] 2016-01-21 08:07
> It might have something to do with caching, as after restarting the CLI the problem always disappears - get_account xxxx gives the correct response.

I noticed that as well in local testnets. Upgrade membership only gets recognized after a cli-wallet restart.

**Comment by theoreticalbts** [comment] 2016-02-08 15:17
This is one of many different issues caused by `cli_wallet` cache logic not working properly.  For now the workaround is to restart `cli_wallet`.

**Comment by theoreticalbts** [comment] 2016-02-16 04:05
Closing because this is a symptom of #530 and will be fixed when #530 is fixed.

**Closed as completed by theoreticalbts** 2016-02-16 04:05 UTC
