### ISSUE TITLE
Can't remove negative votes or do any votes at all

### ISSUE THREAD

**Issue by mindphlux1** [cryptonomex/graphene#642] opened 2016-03-30 06:14 UTC
Ever since the negative votes were removed, I cannot vote anymore. Svk told me I must remove my negative votes first, but this doesn't work for me as well.

I have these negative votes: "1.14.10", "1.14.11", "1.14.12", "1.14.13", "1.14.14", "1.14.15", "1.14.0"

I try to remove them with:

update_worker_votes mindphlux {"vote_abstain": ["1.14.10", "1.14.11", "1.14.12", "1.14.13", "1.14.14", "1.14.15", "1.14.0"]} true

0 exception: unspecified
10 assert_exception: Assert Exception
against_worker_idx.find( id ) == against_worker_idx.end():
    {}
    th_a  account_evaluator.cpp:87 verify_account_votes

I also can't vote for or against these workers or any other worker at present time.

Thanks!

**Comment by abitmore** [comment] 2016-03-30 08:46
Duplicate of #638? Also see GUI issue https://github.com/cryptonomex/graphene-ui/issues/798.

The voting command set in CLI is known to be not working well, it need a overall redesign.

Before GUI fix is ready, try following steps with CLI to clear all votes as a workaround:

```
>>> begin_builder_transaction
>>> add_operation_to_builder_transaction 0 [6,{"fee": {"amount": 0,"asset_id": "1.3.0"},"account": "1.2.you_account_id","new_options": {"memo_key": "your_memo_key","voting_account": "1.2.5","num_witness": 0,"num_committee": 0,"votes": [],"extensions": []},"extensions": {}}]
>>> set_fees_on_builder_transaction 0 1.3.0
>>> sign_builder_transaction 0 true
```

then vote in GUI.

**Comment by vikramrajkumar** [comment] 2017-01-18 02:48
This issue was moved to bitshares/bitshares-core#204

**Closed as completed by vikramrajkumar** 2017-01-18 02:49 UTC
