### ISSUE TITLE
Cannot send transactions in latest build

### ISSUE THREAD

**Issue by wildbunny** [cryptonomex/graphene#487] opened 2015-12-18 10:03 UTC
I get the following asset every time I try to send a transaction:

{code:1,message:10 assert_exception:Assert Exception
my->_key != empty_pub:  
    {}
    th_a  elliptic_secp256k1.cpp:118 serialize

```
{"from":"metaexchangebtc","to":"usd-collateral-holder-453","amount":"12206.79294","asset_symbol":"BTS","memo":"mX: buy BTS_BTC","broadcast":true}
th_a  wallet.cpp:2002 transfer,data:{code:10,name:assert_exception,message:Assert Exception,stack:[{context:{level:error,file:elliptic_secp256k1.cpp,line:118,method:serialize,hostname:,thread_name:th_a,timestamp:2015-12-17T00:38:13},format:my->_key != empty_pub: ,data:{}},{context:{level:warn,file:wallet.cpp,line:2002,method:transfer,hostname:,thread_name:th_a,timestamp:2015-12-17T00:38:13},format:,data:{from:metaexchangebtc,to:usd-collateral-holder-453,amount:12206.79294,asset_symbol:BTS,memo:mX: buy BTS_BTC,broadcast:true}}]}}
```

**Comment by wildbunny** [comment] 2015-12-18 16:01
This appears to be localised to this particular recepient account. I suspect the object id shuffle is a candidate cause for this.

More info: https://bitsharestalk.org/index.php/topic,20683.0.html

**Comment by theoreticalbts** [comment] 2016-01-04 20:21
The memo key for collateral holder accounts isn't being initialized in the genesis.  This should be fixed.

**Comment by theoreticalbts** [comment] 2016-02-09 10:49
We can't register a memo key for collateral holder accounts because they only have an address, not a key.  The real problem is #377 -- the wallet gets confused trying to create a memo for an account without a memo key.  Try sending with an empty memo.

Closing as duplicate of #377

**Closed as completed by theoreticalbts** 2016-02-09 10:49 UTC
Labels: bug
