### ISSUE TITLE
[API] CLI Wallet needs a method to get account history since head

### ISSUE THREAD

**Issue by ByronAP** [cryptonomex/graphene#397] opened 2015-10-25 19:38 UTC
Using the cli wallet get_account_history is limited to the last 100 transactions this is not that many which can lead to missed transactions, wasted bandwidth and time searching through unneeded records.

A method like get_account_history_since_head(headnumber) would fix this problem and save resources.

**Comment by theoreticalbts** [comment] 2015-11-20 17:03
Duplicate of #326

**Closed as completed by theoreticalbts** 2015-11-20 17:03 UTC
