### ISSUE TITLE
[API] get_account_history unnecessarily restricts result size

### ISSUE THREAD

**Issue by wildbunny** [cryptonomex/graphene#389] opened 2015-10-22 09:10 UTC
get_account_histroy contains a FC_ASSERT(limit <= 100) which prevents retrieving more than 100 results at any one time. As the owner of my own witness, **I** should be able to decide how many results this function returns, regardless of performance degradation to my own hardware.

**Comment by theoreticalbts** [comment] 2015-11-20 17:03
Duplicate of #326

**Closed as completed by theoreticalbts** 2015-11-20 17:03 UTC
