### ISSUE TITLE
CLI wallet command "get_account" doesn't show correct voting info if voted in cli-wallet

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene#331] opened 2015-09-19 18:35 UTC
```
unlocked >>> vote_for_witness in.abit in.abit true true
vote_for_witness in.abit in.abit true true
{
  "ref_block_num": 26444,
  "ref_block_prefix": 2220969320,
  "expiration": "2015-09-19T18:30:39",
  "operations": [[
      6,{
        "fee": {
          "amount": 1002929,
          "asset_id": "1.3.0"
        },
        "account": "1.2.38993",
        "new_options": {
          "memo_key": "GPH7SakKqZ8HamkTr7FdPn9qYxYmtSh2QzFNn49CiFAkdFAvQVMg6",
          "voting_account": "1.2.5",
          "num_witness": 0,
          "num_committee": 0,
          "votes": [
            "1:5267"
          ],
          "extensions": []
        },
        "extensions": []
      }
    ]
  ],
  "extensions": [],
  "signatures": [
    "20343d8dff9e2eabb5a3f100941dfcf0720062267806aff30f6ff85d3b04099c0741b3553fc6fe40582c523d2c8e3e3a2abfe8836e879c028116a8ade385c6e0$
b"
  ]
}
unlocked >>> get_account in.abit
get_account in.abit
{
  "id": "1.2.38993",
...
  "name": "in.abit",
...
  "options": {
    "memo_key": "GPH7SakKqZ8HamkTr7FdPn9qYxYmtSh2QzFNn49CiFAkdFAvQVMg6",
    "voting_account": "1.2.5",
    "num_witness": 0,
    "num_committee": 0,
    "votes": [],
    "extensions": []
  },
...
```

**Comment by abitmore** [comment] 2015-09-19 19:50
Maybe duplicate of #323

**Comment by abitmore** [comment] 2015-09-19 20:05
According to #323, it's because of the `votes` data is not refreshed from chain.

However, although the `votes` array is correctly showed in other clients, the `num_witness` or `num_committee` is incorrect.

```
  "options": {
    "memo_key": "GPH7SakKqZ8HamkTr7FdPn9qYxYmtSh2QzFNn49CiFAkdFAvQVMg6",
    "voting_account": "1.2.5",
    "num_witness": 0,
    "num_committee": 0,
    "votes": [
      "0:5269"
    ],
    "extensions": []
  },
```

**Comment by theoreticalbts** [comment] 2015-09-22 19:04
As well as voting for witnesses and committee members, the blockchain allows you to vote for how many you want there to be.  If you vote for 0, it is the same as voting for the minimum size (11).

However, this function is not exposed in the cli wallet.  The voting command needs to be re-written.

**Comment by abitmore** [comment] 2015-09-23 00:59
There is a command `set_desired_witness_and_committee_member_count` in CLI wallet.

**Comment by theoreticalbts** [comment] 2016-02-03 16:35
Closing as duplicate of #323

**Closed as completed by theoreticalbts** 2016-02-03 16:35 UTC
Labels: client
