### ISSUE TITLE
parse_error_exception: Parse Error, on every command

### ISSUE THREAD

**Issue by maqifrnswa** [cryptonomex/graphene#107] opened 2015-06-29 15:49 UTC
$ ./cli_wallet 
Logging RPC to file: logs/rpc/rpc.log
2736591ms th_a       main.cpp:107                  main                 ] key_to_wif( genesis_private_key ): 5KCBDTcyDqzsqehcb52tW5nU6pXife6V2rX9Yf7c3saYSzbDZ5W 
2736598ms th_a       main.cpp:110                  main                 ] key_to_wif( nathan_private_key ): 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3 
Please use the set_password method to initialize a new wallet before continuing
2736819ms th_a       thread.cpp:95                 thread               ] name:getline tid:3038766160
new >>> set_password test
set_password test
4 parse_error_exception: Parse Error
Unexpected char '255' in ""
    {"c":255,"s":""}
    th_a  json_relaxed.hpp:738 variant_from_stream

```
{"str":"set_password test�"}
th_a  json.cpp:494 variants_from_string
```

**Comment by theoreticalbts** [comment] 2015-06-29 16:25
I can't reproduce this.  Try this:
- Update FC ( `git submodule update` )
- Remove `wallet.json`, be sure to back up private keys first ( may be duplicate of #64 )
- Remove `witness_node_data_dir` (keep `config.ini` of course)

What OS are you using?

**Comment by maqifrnswa** [comment] 2015-06-29 17:26
Raspbian jessie:
https://bitsharestalk.org/index.php/topic,17297.msg220235.html#msg220235

I'm thinking 0xFF is being appended on to the string from somewhere? I can't find it happening on other SSH or armhf systems.

From the command line, it looks fine:

```
$ echo -ne 'AAAAAAAA
' | python -c 'import sys; print repr(sys.stdin.read())'`
```

Gives: `'AAAAAAAA\n'`

it may take a while for me to test it with the newest FC and code, as it's not that straight forward getting code on there at the moment.

**Comment by maqifrnswa** [comment] 2015-06-29 20:37
I did all three of theoretical's steps, still happens. It also happens if I don't SSH but just log in at the terminal. Some library seems to be messing up the input? I'll keep trying to hunt it down

**Comment by pmconrad** [comment] 2015-06-30 10:25
Did you build with or without readline? Does it also happen when you pipe commands into the wallet, like
`(echo set_password test; echo info; sleep 6 ) | ./cli_wallet`

**Comment by maqifrnswa** [comment] 2015-06-30 13:24
Built with readline
(from CMakeCache.txt:
READLINE_LIBRARIES:FILEPATH=/usr/lib/arm-linux-gnueabihf/libreadline.so)

When I pipe the command, it still happens:

```
$ (echo set_password test; echo info; sleep 6 ) | ./cli_wallet
locked >>> set_password test
4 parse_error_exception: Parse Error
Unexpected char '255' in ""
    {"c":255,"s":""}
    th_a  json_relaxed.hpp:738 variant_from_stream

    {"str":"set_password test�"}
    th_a  json.cpp:494 variants_from_string
locked >>> info
4 parse_error_exception: Parse Error
Unexpected char '255' in ""
    {"c":255,"s":""}
    th_a  json_relaxed.hpp:738 variant_from_stream

    {"str":"info�"}
    th_a  json.cpp:494 variants_from_string
```

thank you

**Comment by bytemaster** [comment] 2015-07-01 19:48
Until we have some proof that this is not a shell bug this is low priority.

**Comment by maqifrnswa** [comment] 2015-07-03 16:01
Might have found something:
istream.peak() returns an int, but json_relaxed.hpp and json.cpp both have `char c = in.peek()`
which is ok on x86 where char is signed, but on ARM char is unsigned
when parsing EOF (signed char=-1), it will be read as unsigned char=255, thus triggering the "unexpected character" warning

Since graphene moved to boost 1.57, my ARM build machine is borked. I set up another one based on debian experimental, and it is building - it will take a while for me to confirm this bug on that machine and then try the fix. I just wanted to share in case someone sees an obvious reason why this shouldn't work (and save me a lot of time!)

**Comment by maqifrnswa** [comment] 2015-07-05 19:56
Above pull request fixes this.

peek() returns an int, but is being casted to an unsigned char which causes the above bug. char is not defined as signed or unsigned, so each architecture may do it differently. x86 have signed chars, ARM have unsigned. Using EOF in case statements requires signed chars, thus this failure on ARM.

Alternatively, you can use the gcc flag "-fsigned-char" to force all chars to be signed. Up to you whether you want this patch of the gcc flag. I prefer the patch since the flag would just mask a portability problem that might bite us again later down the road.

In the future, there is a compiler warning that pops up during building illustrates this problem, which I didn't realize until testing:

```
[ 12%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/io/json.cpp.o
/home/pi/bitshares/graphene/libraries/fc/src/io/json.cpp: In instantiation of ‘fc::variant fc::variant_from_stream(T&) [with T = fc::stringstream; fc::json::parse_type parser_type = (fc::json::parse_type)0u]’:
/home/pi/bitshares/graphene/libraries/fc/src/io/json.cpp:468:79:   required from here
/home/pi/bitshares/graphene/libraries/fc/src/io/json.cpp:428:13: warning: case label value is less than minimum value for type
             case EOF:
```

With this patch the compiler warning goes away, and the cli_wallet is responsive:

```
locked >>> info
{
  "head_block_num": 3,
  "head_block_id": "0000000394351c6e35a3c184feffa2d751b15eea",
  "head_block_age": "0 second old",
  "next_maintenance_time": "4 hours in the future",
  "chain_id": "11f66de67ebabef1fbee642c3a1c49f6e00df3ac12f5ae3f8b530d3554593847",
  "active_witnesses": [
    "1.6.0",
    "1.6.1",
    "1.6.2",
    "1.6.3",
    "1.6.4",
    "1.6.5",
    "1.6.6",
    "1.6.7",
    "1.6.8",
    "1.6.9"
  ],
  "active_delegates": [
    "1.5.8",
    "1.5.9",
    "1.5.4",
    "1.5.7",
    "1.5.5",
    "1.5.3",
    "1.5.1",
    "1.5.0",
    "1.5.2",
    "1.5.6"
  ],
  "entropy": "edb63d39e5898d2fff11e4213f0cf80a744393a5a5dde9c747e0cdeb"
}
```

**Closed as completed** 2015-07-06 16:12 UTC
Labels: wontfix
